use std::collections::BTreeSet;
use std::fmt::Write;

use super::{
    DecoderNode, DeltaCoding, EncodedColumn, NullPlacement, OutputGuarantee, PlanOp, Predicate,
    Query, Span, compile, primitive_rule_fingerprint,
};

pub fn generate_rust_module(columns: &[EncodedColumn]) -> Result<String, String> {
    if columns.is_empty() {
        return Err("cannot generate an empty access-plan module".into());
    }
    let mut source = String::new();
    writeln!(
        source,
        "// Generated by generate_access_compiler. Do not edit."
    )
    .unwrap();
    writeln!(source, "use witness::access_compiler::{{AccessMetrics, Answer, ClosureMode, EncodedColumn, Execution, FieldId, NullPlacement, ReadSession, Span, StaticBitPack, StaticDelta, StaticDictionary, StaticFor, StaticNullable, StaticPatch, StaticRle, find_position, load_metadata, locate_indexed, lower_bound_position, nullable_is_valid, nullable_prefix_rank, nullable_rank, push_range, static_between, static_dictionary_filter, static_get, static_monotone_filter, static_piecewise_monotone_filter, static_sum, unzigzag}};").unwrap();
    writeln!(
        source,
        "pub const RULE_FINGERPRINT: u64 = {:#018x};",
        primitive_rule_fingerprint()
    )
    .unwrap();
    writeln!(source, "pub const CASE_COUNT: usize = {};", columns.len()).unwrap();
    for (case, column) in columns.iter().enumerate() {
        let plan_signature = validate_plan_contract(column)?;
        writeln!(
            source,
            "pub const C{case:02}_PLAN_SIGNATURE: u64 = {plan_signature:#018x};"
        )
        .unwrap();
        let mut visits = BTreeSet::new();
        mark_visits(column, column.decoder.root().0, &mut visits)?;
        for (node_id, node) in column.decoder.nodes().iter().enumerate() {
            emit_static_alias(&mut source, case, node_id, node);
            emit_get(&mut source, case, node_id, node)?;
            if visits.contains(&node_id) {
                emit_visit(&mut source, case, node_id, node)?;
            }
        }
        let filter_plan = compile(
            column,
            Query::Filter {
                predicate: Predicate::Between {
                    low: i64::MIN,
                    high: i64::MAX,
                },
            },
        )?;
        let filter_lowering = filter_plan
            .nodes
            .iter()
            .find_map(|node| match node.op {
                PlanOp::SearchMonotone { nulls } => Some(FilterLowering::Monotone(nulls)),
                PlanOp::SearchPiecewiseMonotone { max_rows } => {
                    Some(FilterLowering::Piecewise(max_rows))
                }
                PlanOp::TranslateDictionaryRange {
                    dictionary,
                    entries,
                } => match column.decoder.node(column.decoder.root()).ok()? {
                    DecoderNode::Dictionary { ids, .. } => Some(FilterLowering::Dictionary {
                        ids: ids.0,
                        dictionary: dictionary.0,
                        entries,
                    }),
                    _ => None,
                },
                _ => None,
            })
            .unwrap_or(FilterLowering::Scan);
        emit_queries(&mut source, case, column.decoder.root().0, filter_lowering)?;
    }
    emit_registries(&mut source, columns.len());
    Ok(source)
}

fn validate_plan_contract(column: &EncodedColumn) -> Result<u64, String> {
    let len = column.truth.len();
    let full = Span::new(0, len)?;
    let contracts = [
        (
            Query::Get { row: 0 },
            OutputGuarantee::ExactScalar,
            PlanOp::MaterializeRows,
        ),
        (
            Query::Sum { rows: full },
            OutputGuarantee::ExactScalar,
            PlanOp::AggregateEncoded,
        ),
        (
            Query::Between {
                rows: full,
                low: i64::MIN,
                high: i64::MAX,
            },
            OutputGuarantee::ExactBitmap,
            PlanOp::RefineCandidates,
        ),
        (
            Query::Filter {
                predicate: Predicate::Between {
                    low: i64::MIN,
                    high: i64::MAX,
                },
            },
            OutputGuarantee::ExactBitmap,
            PlanOp::RefineCandidates,
        ),
    ];
    let mut hash = 0xcbf2_9ce4_8422_2325_u64;
    for (query, guarantee, final_op) in contracts {
        let plan = compile(column, query)?;
        if plan.output != guarantee || plan.nodes.last().map(|node| &node.op) != Some(&final_op) {
            return Err("Plan IR cannot authorize generated exact-query lowering".into());
        }
        for byte in format!("{plan:?}").bytes() {
            hash = (hash ^ u64::from(byte)).wrapping_mul(0x1000_0000_01b3);
        }
    }
    Ok(hash)
}

fn mark_visits(
    column: &EncodedColumn,
    node: usize,
    visits: &mut BTreeSet<usize>,
) -> Result<(), String> {
    if !visits.insert(node) {
        return Ok(());
    }
    match column.decoder.node(super::NodeId(node))? {
        DecoderNode::For { values, .. }
        | DecoderNode::Delta { deltas: values, .. }
        | DecoderNode::Patch { values, .. }
        | DecoderNode::Nullable { values, .. } => mark_visits(column, values.0, visits),
        DecoderNode::Dictionary { ids, .. } => mark_visits(column, ids.0, visits),
        _ => Ok(()),
    }
}

fn emit_static_alias(source: &mut String, case: usize, node: usize, decoder: &DecoderNode) {
    let alias = static_name(case, node);
    let value = match decoder {
        DecoderNode::BitUnpack {
            stream,
            width,
            miniblock_rows,
            miniblock_bytes,
            ..
        } => format!(
            "StaticBitPack<{}, {}, {}, {}>",
            stream.0, width, miniblock_rows, miniblock_bytes
        ),
        DecoderNode::For { base, values } => {
            format!("StaticFor<{}, {}>", base.0, static_name(case, values.0))
        }
        DecoderNode::Delta {
            deltas,
            restarts,
            restart_interval,
            coding,
            ..
        } => format!(
            "StaticDelta<{}, {}, {}, {}>",
            restarts.0,
            restart_interval,
            *coding == DeltaCoding::Unsigned,
            static_name(case, deltas.0)
        ),
        DecoderNode::Rle {
            values,
            run_lengths,
            run_index,
            runs,
            index_interval,
            ..
        } => format!(
            "StaticRle<{}, {}, {}, {}, {}>",
            run_lengths.0,
            run_index.0,
            runs,
            index_interval,
            static_name(case, values.0)
        ),
        DecoderNode::Dictionary {
            ids,
            dictionary,
            entries,
            ..
        } => format!(
            "StaticDictionary<{}, {}, {}>",
            dictionary.0,
            entries,
            static_name(case, ids.0)
        ),
        DecoderNode::Patch {
            values,
            positions,
            position_index,
            exceptions,
            count,
            index_interval,
        } => format!(
            "StaticPatch<{}, {}, {}, {}, {}, {}>",
            positions.0,
            position_index.0,
            exceptions.0,
            count,
            index_interval,
            static_name(case, values.0)
        ),
        DecoderNode::Nullable {
            validity,
            rank_index,
            values,
            rank_interval,
            ..
        } => format!(
            "StaticNullable<{}, {}, {}, {}>",
            validity.0,
            rank_index.0,
            rank_interval,
            static_name(case, values.0)
        ),
    };
    writeln!(source, "type {alias} = {value};").unwrap();
}

fn emit_get(
    source: &mut String,
    case: usize,
    node: usize,
    decoder: &DecoderNode,
) -> Result<(), String> {
    let name = get_name(case, node);
    writeln!(source, "#[inline(always)]").unwrap();
    writeln!(
        source,
        "fn {name}(session: &mut ReadSession<'_>, row: usize) -> Result<Option<i128>, String> {{"
    )
    .unwrap();
    match decoder {
        DecoderNode::BitUnpack {
            stream,
            width,
            miniblock_rows,
            miniblock_bytes,
            ..
        } => writeln!(
            source,
            "    Ok(Some(i128::from(session.read_bits(FieldId({}), row, {}, {}, {})?)))",
            stream.0, width, miniblock_rows, miniblock_bytes
        )
        .unwrap(),
        DecoderNode::For { base, values } => {
            writeln!(
                source,
                "    let base = i128::from(session.read_i64(FieldId({}), 0)?);",
                base.0
            )
            .unwrap();
            writeln!(
                source,
                "    match {}(session, row)? {{",
                get_name(case, values.0)
            )
            .unwrap();
            writeln!(source, "        Some(value) => Ok(Some(value.checked_add(base).ok_or(\"generated FOR overflow\")?)),").unwrap();
            writeln!(source, "        None => Ok(None),").unwrap();
            writeln!(source, "    }}").unwrap();
        }
        DecoderNode::Delta {
            deltas,
            restarts,
            restart_interval,
            coding,
            ..
        } => {
            writeln!(source, "    let block = row / {restart_interval};").unwrap();
            writeln!(source, "    let block_start = block * {restart_interval};").unwrap();
            writeln!(
                source,
                "    let mut value = i128::from(session.read_i64(FieldId({}), block)?);",
                restarts.0
            )
            .unwrap();
            writeln!(source, "    if block_start < row {{ {}(session, block_start + 1, row + 1, &mut |_session, code, start, end| {{", visit_name(case, deltas.0)).unwrap();
            emit_generated_delta(source, *coding, "        ");
            writeln!(source, "        for _ in start..end {{ value = value.checked_add(delta).ok_or(\"generated delta overflow\")?; }} Ok(())").unwrap();
            writeln!(source, "    }})?; }}").unwrap();
            writeln!(source, "    Ok(Some(value))").unwrap();
        }
        DecoderNode::Rle {
            values,
            run_lengths,
            run_index,
            runs,
            index_interval,
            ..
        } => {
            writeln!(source, "    let (run, _, _) = locate_indexed(session, FieldId({}), FieldId({}), {}, {}, row)?;", run_index.0, run_lengths.0, runs, index_interval).unwrap();
            writeln!(source, "    {}(session, run)", get_name(case, values.0)).unwrap();
        }
        DecoderNode::Dictionary {
            ids,
            dictionary,
            entries,
            ..
        } => {
            writeln!(source, "    let id = usize::try_from({}(session, row)?.ok_or(\"generated dictionary id is null\")?).map_err(|_| \"generated dictionary id does not fit usize\")?;", get_name(case, ids.0)).unwrap();
            writeln!(source, "    if id >= {entries} {{ return Err(\"generated dictionary id is outside table\".into()); }}").unwrap();
            writeln!(
                source,
                "    Ok(Some(i128::from(session.read_i64(FieldId({}), id)?)))",
                dictionary.0
            )
            .unwrap();
        }
        DecoderNode::Patch {
            values,
            positions,
            position_index,
            exceptions,
            count,
            index_interval,
        } => {
            writeln!(
                source,
                "    match find_position(session, FieldId({}), FieldId({}), {}, {}, row)? {{",
                position_index.0, positions.0, count, index_interval
            )
            .unwrap();
            writeln!(source, "        Some(exception) => Ok(Some(i128::from(session.read_i64(FieldId({}), exception)?))),", exceptions.0).unwrap();
            writeln!(
                source,
                "        None => {}(session, row),",
                get_name(case, values.0)
            )
            .unwrap();
            writeln!(source, "    }}").unwrap();
        }
        DecoderNode::Nullable {
            validity,
            rank_index,
            values,
            rank_interval,
            ..
        } => {
            writeln!(
                source,
                "    match nullable_rank(session, FieldId({}), FieldId({}), row, {})? {{",
                validity.0, rank_index.0, rank_interval
            )
            .unwrap();
            writeln!(
                source,
                "        Some(compact_row) => {}(session, compact_row),",
                get_name(case, values.0)
            )
            .unwrap();
            writeln!(source, "        None => Ok(None),").unwrap();
            writeln!(source, "    }}").unwrap();
        }
    }
    writeln!(source, "}}\n").unwrap();
    Ok(())
}

fn emit_visit(
    source: &mut String,
    case: usize,
    node: usize,
    decoder: &DecoderNode,
) -> Result<(), String> {
    let name = visit_name(case, node);
    writeln!(source, "#[inline(always)]").unwrap();
    writeln!(source, "fn {name}<F>(session: &mut ReadSession<'_>, start: usize, end: usize, visitor: &mut F) -> Result<(), String> where F: FnMut(&mut ReadSession<'_>, Option<i128>, usize, usize) -> Result<(), String> {{").unwrap();
    match decoder {
        DecoderNode::BitUnpack {
            stream,
            width,
            miniblock_rows,
            miniblock_bytes,
            ..
        } => {
            writeln!(source, "    let values = session.read_bit_values(FieldId({}), Span::new(start, end)?, {}, {}, {})?;", stream.0, width, miniblock_rows, miniblock_bytes).unwrap();
            writeln!(source, "    for (offset, value) in values.into_iter().enumerate() {{ let row = start + offset; visitor(session, Some(i128::from(value)), row, row + 1)?; }}").unwrap();
            writeln!(source, "    Ok(())").unwrap();
        }
        DecoderNode::For { base, values } => {
            writeln!(
                source,
                "    let base = i128::from(session.read_i64(FieldId({}), 0)?);",
                base.0
            )
            .unwrap();
            writeln!(
                source,
                "    {}(session, start, end, &mut |session, value, span_start, span_end| {{",
                visit_name(case, values.0)
            )
            .unwrap();
            writeln!(source, "        let value = value.map(|value| value.checked_add(base).ok_or(\"generated FOR span overflow\")).transpose()?;").unwrap();
            writeln!(
                source,
                "        visitor(session, value, span_start, span_end)"
            )
            .unwrap();
            writeln!(source, "    }})").unwrap();
        }
        DecoderNode::Delta {
            deltas,
            restarts,
            restart_interval,
            coding,
            ..
        } => {
            writeln!(
                source,
                "    let mut block_start = start / {restart_interval} * {restart_interval};"
            )
            .unwrap();
            writeln!(source, "    while block_start < end {{").unwrap();
            writeln!(
                source,
                "        let block_end = (block_start + {restart_interval}).min(end);"
            )
            .unwrap();
            writeln!(source, "        let emit_start = start.max(block_start);").unwrap();
            writeln!(source, "        let mut value = i128::from(session.read_i64(FieldId({}), block_start / {})?);", restarts.0, restart_interval).unwrap();
            writeln!(source, "        if block_start >= emit_start {{ visitor(session, Some(value), block_start, block_start + 1)?; }}").unwrap();
            writeln!(source, "        if block_start + 1 < block_end {{ {}(session, block_start + 1, block_end, &mut |session, code, span_start, span_end| {{", visit_name(case, deltas.0)).unwrap();
            emit_generated_delta(source, *coding, "            ");
            writeln!(source, "            for row in span_start..span_end {{ value = value.checked_add(delta).ok_or(\"generated delta span overflow\")?; if row >= emit_start {{ visitor(session, Some(value), row, row + 1)?; }} }} Ok(())").unwrap();
            writeln!(source, "        }})?; }}").unwrap();
            writeln!(source, "        block_start += {restart_interval};").unwrap();
            writeln!(source, "    }}").unwrap();
            writeln!(source, "    Ok(())").unwrap();
        }
        DecoderNode::Rle {
            values,
            run_lengths,
            run_index,
            runs,
            index_interval,
            ..
        } => {
            writeln!(source, "    if start == end {{ return Ok(()); }}").unwrap();
            writeln!(source, "    let (mut run, mut run_start, _) = locate_indexed(session, FieldId({}), FieldId({}), {}, {}, start)?;", run_index.0, run_lengths.0, runs, index_interval).unwrap();
            writeln!(source, "    while run < {runs} && run_start < end {{").unwrap();
            writeln!(source, "        let run_end = run_start.checked_add(session.read_u32(FieldId({}), run)? as usize).ok_or(\"generated RLE row overflow\")?;", run_lengths.0).unwrap();
            writeln!(source, "        let span_start = start.max(run_start);").unwrap();
            writeln!(source, "        let span_end = end.min(run_end);").unwrap();
            writeln!(source, "        if span_start < span_end {{ let value = {}(session, run)?; visitor(session, value, span_start, span_end)?; }}", get_name(case, values.0)).unwrap();
            writeln!(source, "        run_start = run_end; run += 1;").unwrap();
            writeln!(source, "    }}").unwrap();
            writeln!(source, "    Ok(())").unwrap();
        }
        DecoderNode::Dictionary {
            ids,
            dictionary,
            entries,
            ..
        } => {
            writeln!(
                source,
                "    {}(session, start, end, &mut |session, id, span_start, span_end| {{",
                visit_name(case, ids.0)
            )
            .unwrap();
            writeln!(source, "        let id = usize::try_from(id.ok_or(\"generated dictionary id is null\")?).map_err(|_| \"generated dictionary id does not fit usize\")?;").unwrap();
            writeln!(source, "        if id >= {entries} {{ return Err(\"generated dictionary id is outside table\".into()); }}").unwrap();
            writeln!(source, "        let value = Some(i128::from(session.read_i64(FieldId({}), id)?)); visitor(session, value, span_start, span_end)", dictionary.0).unwrap();
            writeln!(source, "    }})").unwrap();
        }
        DecoderNode::Patch {
            values,
            positions,
            position_index,
            exceptions,
            count,
            index_interval,
        } => {
            writeln!(source, "    let mut exception = lower_bound_position(session, FieldId({}), FieldId({}), {}, {}, start)?;", position_index.0, positions.0, count, index_interval).unwrap();
            writeln!(source, "    let mut patches = Vec::new();").unwrap();
            writeln!(source, "    while exception < {count} {{ let row = session.read_u32(FieldId({}), exception)? as usize; if row >= end {{ break; }} patches.push((row, i128::from(session.read_i64(FieldId({}), exception)?))); exception += 1; }}", positions.0, exceptions.0).unwrap();
            writeln!(source, "    let mut patch = 0;").unwrap();
            writeln!(
                source,
                "    {}(session, start, end, &mut |session, value, span_start, span_end| {{",
                visit_name(case, values.0)
            )
            .unwrap();
            writeln!(source, "        let mut cursor = span_start; while patch < patches.len() && patches[patch].0 < span_end {{ let (row, exception) = patches[patch]; if row < cursor {{ return Err(\"generated patch positions are not ordered\".into()); }}\n        if cursor < row {{ visitor(session, value, cursor, row)?; }} visitor(session, Some(exception), row, row + 1)?; cursor = row + 1; patch += 1; }}").unwrap();
            writeln!(source, "        if cursor < span_end {{ visitor(session, value, cursor, span_end)?; }} Ok(())").unwrap();
            writeln!(source, "    }})").unwrap();
        }
        DecoderNode::Nullable {
            validity,
            rank_index,
            values,
            rank_interval,
            ..
        } => {
            writeln!(source, "    let mut logical = start; let mut compact = nullable_prefix_rank(session, FieldId({}), FieldId({}), start, {})?;", validity.0, rank_index.0, rank_interval).unwrap();
            writeln!(source, "    while logical < end {{ let valid = nullable_is_valid(session, FieldId({}), logical)?; let run_start = logical; logical += 1; while logical < end && nullable_is_valid(session, FieldId({}), logical)? == valid {{ logical += 1; }}", validity.0, validity.0).unwrap();
            writeln!(source, "        if valid {{ let child_start = compact; compact += logical - run_start; {}(session, child_start, compact, &mut |session, value, span_start, span_end| {{ let mapped_start = run_start + span_start - child_start; visitor(session, value, mapped_start, mapped_start + span_end - span_start) }})?; }} else {{ visitor(session, None, run_start, logical)?; }}", visit_name(case, values.0)).unwrap();
            writeln!(source, "    }} Ok(())").unwrap();
        }
    }
    writeln!(source, "}}\n").unwrap();
    Ok(())
}

fn emit_generated_delta(source: &mut String, coding: DeltaCoding, indent: &str) {
    writeln!(source, "{indent}let code = u64::try_from(code.ok_or(\"generated delta code is null\")?).map_err(|_| \"generated delta code does not fit u64\")?;").unwrap();
    match coding {
        DeltaCoding::ZigZag => {
            writeln!(source, "{indent}let delta = i128::from(unzigzag(code));").unwrap();
        }
        DeltaCoding::Unsigned => {
            writeln!(source, "{indent}let delta = i128::from(code);").unwrap();
        }
    }
}

fn emit_queries(
    source: &mut String,
    case: usize,
    root: usize,
    filter_lowering: FilterLowering,
) -> Result<(), String> {
    let get = get_name(case, root);
    let visit = visit_name(case, root);
    writeln!(source, "pub fn c{case:02}_get_session(column: &EncodedColumn, row: usize, session: &mut ReadSession<'_>) -> Result<Execution, String> {{").unwrap();
    writeln!(source, "    if row >= column.truth.len() {{ return Err(\"generated GET outside column\".into()); }}").unwrap();
    writeln!(source, "    load_metadata(&column.page, session)?;").unwrap();
    writeln!(source, "    let value = {get}(session, row)?.map(|value| i64::try_from(value).map_err(|_| \"generated GET value does not fit i64\")).transpose()?;").unwrap();
    writeln!(source, "    Ok(Execution {{ answer: Answer::Value(value), metrics: session.metrics(), decoded_rows: 1 }})").unwrap();
    writeln!(source, "}}\n").unwrap();
    writeln!(source, "pub fn c{case:02}_get(column: &EncodedColumn, row: usize, mode: ClosureMode) -> Result<Execution, String> {{ let mut session = ReadSession::new(&column.page, mode); c{case:02}_get_session(column, row, &mut session) }}\n").unwrap();

    writeln!(source, "pub fn c{case:02}_sum_session(column: &EncodedColumn, rows: Span, session: &mut ReadSession<'_>) -> Result<Execution, String> {{").unwrap();
    writeln!(source, "    if rows.start > rows.end || rows.end > column.truth.len() {{ return Err(\"generated SUM range invalid\".into()); }}").unwrap();
    writeln!(
        source,
        "    load_metadata(&column.page, session)?; let mut sum = 0_i128; let mut decoded_rows = 0;"
    )
    .unwrap();
    writeln!(source, "    {visit}(session, rows.start, rows.end, &mut |_session, value, start, end| {{ decoded_rows += end - start; if let Some(value) = value {{ sum = sum.checked_add(value.checked_mul((end - start) as i128).ok_or(\"generated SUM product overflow\")?).ok_or(\"generated SUM overflow\")?; }} Ok(()) }})?;").unwrap();
    writeln!(
        source,
        "    Ok(Execution {{ answer: Answer::Sum(sum), metrics: session.metrics(), decoded_rows }})"
    )
    .unwrap();
    writeln!(source, "}}\n").unwrap();
    writeln!(source, "pub fn c{case:02}_sum(column: &EncodedColumn, rows: Span, mode: ClosureMode) -> Result<Execution, String> {{ let mut session = ReadSession::new(&column.page, mode); c{case:02}_sum_session(column, rows, &mut session) }}\n").unwrap();

    writeln!(source, "pub fn c{case:02}_between_session(column: &EncodedColumn, rows: Span, low: i64, high: i64, session: &mut ReadSession<'_>) -> Result<Execution, String> {{").unwrap();
    writeln!(source, "    if rows.start > rows.end || rows.end > column.truth.len() || low > high {{ return Err(\"generated BETWEEN invalid\".into()); }}").unwrap();
    writeln!(source, "    load_metadata(&column.page, session)?; let mut ranges = Vec::new(); let mut decoded_rows = 0;").unwrap();
    writeln!(source, "    {visit}(session, rows.start, rows.end, &mut |_session, value, start, end| {{ decoded_rows += end - start; if value.is_some_and(|value| i128::from(low) <= value && value <= i128::from(high)) {{ push_range(&mut ranges, start, end); }} Ok(()) }})?;").unwrap();
    writeln!(source, "    Ok(Execution {{ answer: Answer::Ranges(ranges), metrics: session.metrics(), decoded_rows }})").unwrap();
    writeln!(source, "}}\n").unwrap();
    writeln!(source, "pub fn c{case:02}_between(column: &EncodedColumn, rows: Span, low: i64, high: i64, mode: ClosureMode) -> Result<Execution, String> {{ let mut session = ReadSession::new(&column.page, mode); c{case:02}_between_session(column, rows, low, high, &mut session) }}\n").unwrap();

    writeln!(source, "pub fn c{case:02}_filter_scan_session(column: &EncodedColumn, low: i64, high: i64, session: &mut ReadSession<'_>) -> Result<Execution, String> {{ c{case:02}_between_session(column, Span::new(0, column.truth.len())?, low, high, session) }}").unwrap();
    writeln!(source, "pub fn c{case:02}_filter_scan(column: &EncodedColumn, low: i64, high: i64, mode: ClosureMode) -> Result<Execution, String> {{ let mut session = ReadSession::new(&column.page, mode); c{case:02}_filter_scan_session(column, low, high, &mut session) }}").unwrap();
    if let FilterLowering::Monotone(nulls) = filter_lowering {
        writeln!(source, "pub fn c{case:02}_filter_session(column: &EncodedColumn, low: i64, high: i64, session: &mut ReadSession<'_>) -> Result<Execution, String> {{").unwrap();
        writeln!(source, "    if low > high {{ return Err(\"generated FILTER bounds are invalid\".into()); }} load_metadata(&column.page, session)?; let mut decoded_rows = 0;").unwrap();
        let lower = monotone_comparison(nulls, "value", "i128::from(low)", false);
        let upper = monotone_comparison(nulls, "value", "i128::from(high)", true);
        writeln!(source, "    let mut left = 0; let mut right = column.truth.len(); while left < right {{ let mid = left + (right - left) / 2; let value = {get}(session, mid)?; decoded_rows += 1; if {lower} {{ left = mid + 1; }} else {{ right = mid; }} }} let start = left;").unwrap();
        writeln!(source, "    right = column.truth.len(); while left < right {{ let mid = left + (right - left) / 2; let value = {get}(session, mid)?; decoded_rows += 1; if {upper} {{ left = mid + 1; }} else {{ right = mid; }} }}").unwrap();
        writeln!(source, "    let ranges = if start < left {{ vec![Span::new(start, left)?] }} else {{ Vec::new() }}; Ok(Execution {{ answer: Answer::Ranges(ranges), metrics: session.metrics(), decoded_rows }}) }}").unwrap();
    } else if let FilterLowering::Piecewise(max_rows) = filter_lowering {
        writeln!(source, "pub fn c{case:02}_filter_session(column: &EncodedColumn, low: i64, high: i64, session: &mut ReadSession<'_>) -> Result<Execution, String> {{").unwrap();
        writeln!(source, "    if low > high {{ return Err(\"generated FILTER bounds are invalid\".into()); }} load_metadata(&column.page, session)?; let mut ranges = Vec::new(); let mut decoded_rows = 0;").unwrap();
        writeln!(source, "    let mut block_start = 0; while block_start < column.truth.len() {{ let block_end = (block_start + {max_rows}).min(column.truth.len()); let mut left = block_start; let mut right = block_end; while left < right {{ let mid = left + (right - left) / 2; let value = {get}(session, mid)?.ok_or(\"piecewise monotone block contained null\")?; decoded_rows += 1; if value < i128::from(low) {{ left = mid + 1; }} else {{ right = mid; }} }} let start = left; right = block_end; while left < right {{ let mid = left + (right - left) / 2; let value = {get}(session, mid)?.ok_or(\"piecewise monotone block contained null\")?; decoded_rows += 1; if value <= i128::from(high) {{ left = mid + 1; }} else {{ right = mid; }} }} if start < left {{ push_range(&mut ranges, start, left); }} block_start = block_end; }}").unwrap();
        writeln!(source, "    Ok(Execution {{ answer: Answer::Ranges(ranges), metrics: session.metrics(), decoded_rows }}) }}").unwrap();
    } else if let FilterLowering::Dictionary {
        ids,
        dictionary,
        entries,
    } = filter_lowering
    {
        let ids_visit = visit_name(case, ids);
        writeln!(source, "pub fn c{case:02}_filter_session(column: &EncodedColumn, low: i64, high: i64, session: &mut ReadSession<'_>) -> Result<Execution, String> {{").unwrap();
        writeln!(source, "    if low > high {{ return Err(\"generated FILTER bounds are invalid\".into()); }} load_metadata(&column.page, session)?;").unwrap();
        writeln!(source, "    let mut left = 0; let mut right = {entries}; while left < right {{ let mid = left + (right - left) / 2; if session.read_i64(FieldId({dictionary}), mid)? < low {{ left = mid + 1; }} else {{ right = mid; }} }} let low_id = left;").unwrap();
        writeln!(source, "    right = {entries}; while left < right {{ let mid = left + (right - left) / 2; if session.read_i64(FieldId({dictionary}), mid)? <= high {{ left = mid + 1; }} else {{ right = mid; }} }} let high_id = left;").unwrap();
        writeln!(source, "    let mut ranges = Vec::new(); let mut decoded_rows = 0; if low_id < high_id {{ {ids_visit}(session, 0, column.truth.len(), &mut |_session, id, start, end| {{ decoded_rows += end - start; let id = usize::try_from(id.ok_or(\"generated dictionary id is null\")?).map_err(|_| \"generated dictionary id does not fit usize\")?; if id >= {entries} {{ return Err(\"generated dictionary id is outside table\".into()); }}\nif low_id <= id && id < high_id {{ push_range(&mut ranges, start, end); }} Ok(()) }})?; }}").unwrap();
        writeln!(source, "    Ok(Execution {{ answer: Answer::Ranges(ranges), metrics: session.metrics(), decoded_rows }}) }}").unwrap();
    } else {
        writeln!(source, "pub fn c{case:02}_filter_session(column: &EncodedColumn, low: i64, high: i64, session: &mut ReadSession<'_>) -> Result<Execution, String> {{ c{case:02}_filter_scan_session(column, low, high, session) }}").unwrap();
    }
    writeln!(source, "pub fn c{case:02}_filter(column: &EncodedColumn, low: i64, high: i64, mode: ClosureMode) -> Result<Execution, String> {{ let mut session = ReadSession::new(&column.page, mode); c{case:02}_filter_session(column, low, high, &mut session) }}\n").unwrap();

    emit_sum_ranges(source, case, &visit);

    emit_generated_baselines(source, case, &visit);
    let static_root = static_name(case, root);
    writeln!(source, "pub fn c{case:02}_static_get(column: &EncodedColumn, row: usize, mode: ClosureMode) -> Result<Execution, String> {{ static_get::<{static_root}>(column, row, mode) }}").unwrap();
    writeln!(source, "pub fn c{case:02}_static_sum(column: &EncodedColumn, rows: Span, mode: ClosureMode) -> Result<Execution, String> {{ static_sum::<{static_root}>(column, rows, mode) }}").unwrap();
    writeln!(source, "pub fn c{case:02}_static_between(column: &EncodedColumn, rows: Span, low: i64, high: i64, mode: ClosureMode) -> Result<Execution, String> {{ static_between::<{static_root}>(column, rows, low, high, mode) }}").unwrap();
    match filter_lowering {
        FilterLowering::Monotone(nulls) => writeln!(source, "pub fn c{case:02}_static_filter(column: &EncodedColumn, low: i64, high: i64, mode: ClosureMode) -> Result<Execution, String> {{ static_monotone_filter::<{static_root}>(column, low, high, NullPlacement::{nulls:?}, mode) }}\n").unwrap(),
        FilterLowering::Piecewise(max_rows) => writeln!(source, "pub fn c{case:02}_static_filter(column: &EncodedColumn, low: i64, high: i64, mode: ClosureMode) -> Result<Execution, String> {{ static_piecewise_monotone_filter::<{static_root}>(column, low, high, {max_rows}, mode) }}\n").unwrap(),
        FilterLowering::Dictionary {
            ids,
            dictionary,
            entries,
        } => {
            let static_ids = static_name(case, ids);
            writeln!(source, "pub fn c{case:02}_static_filter(column: &EncodedColumn, low: i64, high: i64, mode: ClosureMode) -> Result<Execution, String> {{ static_dictionary_filter::<{dictionary}, {entries}, {static_ids}>(column, low, high, mode) }}\n").unwrap();
        }
        FilterLowering::Scan => writeln!(source, "pub fn c{case:02}_static_filter(column: &EncodedColumn, low: i64, high: i64, mode: ClosureMode) -> Result<Execution, String> {{ static_between::<{static_root}>(column, Span::new(0, column.truth.len())?, low, high, mode) }}\n").unwrap(),
    }
    Ok(())
}

#[derive(Clone, Copy)]
enum FilterLowering {
    Monotone(NullPlacement),
    Piecewise(usize),
    Dictionary {
        ids: usize,
        dictionary: usize,
        entries: usize,
    },
    Scan,
}

fn monotone_comparison(nulls: NullPlacement, value: &str, bound: &str, inclusive: bool) -> String {
    let comparison = if inclusive { "<=" } else { "<" };
    match nulls {
        NullPlacement::NoNulls => format!(
            "{value}.ok_or(\"dense monotone invariant encountered null\")? {comparison} {bound}"
        ),
        NullPlacement::First => format!("{value}.is_none_or(|value| value {comparison} {bound})"),
        NullPlacement::Last => format!("{value}.is_some_and(|value| value {comparison} {bound})"),
        NullPlacement::Arbitrary => "false".into(),
    }
}

fn emit_sum_ranges(source: &mut String, case: usize, visit: &str) {
    writeln!(source, "fn c{case:02}_validate_ranges(column: &EncodedColumn, ranges: &[Span]) -> Result<(), String> {{ let mut previous = 0; for range in ranges {{ if range.start > range.end || range.end > column.truth.len() || range.start < previous {{ return Err(\"generated selection ranges are invalid\".into()); }} previous = range.end; }} Ok(()) }}").unwrap();
    writeln!(source, "pub fn c{case:02}_sum_ranges_session(column: &EncodedColumn, ranges: &[Span], session: &mut ReadSession<'_>) -> Result<Execution, String> {{").unwrap();
    writeln!(source, "    c{case:02}_validate_ranges(column, ranges)?; load_metadata(&column.page, session)?; let mut sum = 0_i128; let mut decoded_rows = 0;").unwrap();
    writeln!(source, "    for range in ranges {{ {visit}(session, range.start, range.end, &mut |_session, value, start, end| {{ decoded_rows += end - start; if let Some(value) = value {{ sum = sum.checked_add(value.checked_mul((end - start) as i128).ok_or(\"generated selected SUM product overflow\")?).ok_or(\"generated selected SUM overflow\")?; }} Ok(()) }})?; }}").unwrap();
    writeln!(source, "    Ok(Execution {{ answer: Answer::Sum(sum), metrics: session.metrics(), decoded_rows }}) }}").unwrap();
    writeln!(source, "pub fn c{case:02}_sum_ranges(column: &EncodedColumn, ranges: &[Span], mode: ClosureMode) -> Result<Execution, String> {{ let mut session = ReadSession::new(&column.page, mode); c{case:02}_sum_ranges_session(column, ranges, &mut session) }}\n").unwrap();

    writeln!(source, "pub fn c{case:02}_fused_sum_ranges_session(column: &EncodedColumn, ranges: &[Span], session: &mut ReadSession<'_>) -> Result<Execution, String> {{").unwrap();
    writeln!(source, "    c{case:02}_validate_ranges(column, ranges)?; load_metadata(&column.page, session)?; let mut sum = 0_i128; let mut decoded_rows = 0; let mut range_index = 0;").unwrap();
    writeln!(source, "    {visit}(session, 0, column.truth.len(), &mut |_session, value, start, end| {{ decoded_rows += end - start; while range_index < ranges.len() && ranges[range_index].end <= start {{ range_index += 1; }} let mut probe = range_index; while probe < ranges.len() && ranges[probe].start < end {{ let overlap_start = start.max(ranges[probe].start); let overlap_end = end.min(ranges[probe].end); if overlap_start < overlap_end && let Some(value) = value {{ sum = sum.checked_add(value.checked_mul((overlap_end - overlap_start) as i128).ok_or(\"generated fused selected SUM product overflow\")?).ok_or(\"generated fused selected SUM overflow\")?; }}\nif ranges[probe].end <= end {{ probe += 1; }} else {{ break; }} }} range_index = probe; Ok(()) }})?;").unwrap();
    writeln!(source, "    Ok(Execution {{ answer: Answer::Sum(sum), metrics: session.metrics(), decoded_rows }}) }}").unwrap();
    writeln!(source, "pub fn c{case:02}_fused_sum_ranges(column: &EncodedColumn, ranges: &[Span], mode: ClosureMode) -> Result<Execution, String> {{ let mut session = ReadSession::new(&column.page, mode); c{case:02}_fused_sum_ranges_session(column, ranges, &mut session) }}\n").unwrap();
}

fn emit_generated_baselines(source: &mut String, case: usize, visit: &str) {
    emit_materializer(source, case, visit);
    emit_materialized_queries(source, case);
    emit_fused_queries(source, case, visit);
}

fn emit_materializer(source: &mut String, case: usize, visit: &str) {
    writeln!(source, "fn c{case:02}_materialize(column: &EncodedColumn, mode: ClosureMode) -> Result<(Vec<Option<i128>>, AccessMetrics), String> {{").unwrap();
    writeln!(source, "    let mut session = ReadSession::new(&column.page, mode); load_metadata(&column.page, &mut session)?;").unwrap();
    writeln!(
        source,
        "    let mut values = Vec::with_capacity(column.truth.len());"
    )
    .unwrap();
    writeln!(source, "    {visit}(&mut session, 0, column.truth.len(), &mut |_session, value, start, end| {{ for _ in start..end {{ values.push(value); }} Ok(()) }})?;").unwrap();
    writeln!(source, "    if values.len() != column.truth.len() {{ return Err(\"generated materializer returned the wrong row count\".into()); }}").unwrap();
    writeln!(source, "    Ok((values, session.metrics()))").unwrap();
    writeln!(source, "}}\n").unwrap();
}

fn emit_materialized_queries(source: &mut String, case: usize) {
    writeln!(source, "pub fn c{case:02}_materialized_get(column: &EncodedColumn, row: usize, mode: ClosureMode) -> Result<Execution, String> {{").unwrap();
    writeln!(source, "    if row >= column.truth.len() {{ return Err(\"materialized GET outside column\".into()); }} let (values, metrics) = c{case:02}_materialize(column, mode)?;").unwrap();
    writeln!(source, "    let value = values[row].map(|value| i64::try_from(value).map_err(|_| \"materialized GET value does not fit i64\")).transpose()?;").unwrap();
    writeln!(
        source,
        "    Ok(Execution {{ answer: Answer::Value(value), metrics, decoded_rows: values.len() }})"
    )
    .unwrap();
    writeln!(source, "}}\n").unwrap();

    writeln!(source, "pub fn c{case:02}_materialized_sum(column: &EncodedColumn, rows: Span, mode: ClosureMode) -> Result<Execution, String> {{").unwrap();
    writeln!(source, "    if rows.start > rows.end || rows.end > column.truth.len() {{ return Err(\"materialized SUM range invalid\".into()); }} let (values, metrics) = c{case:02}_materialize(column, mode)?; let mut sum = 0_i128;").unwrap();
    writeln!(source, "    for value in values[rows.start..rows.end].iter().flatten() {{ sum = sum.checked_add(*value).ok_or(\"materialized SUM overflow\")?; }}").unwrap();
    writeln!(
        source,
        "    Ok(Execution {{ answer: Answer::Sum(sum), metrics, decoded_rows: values.len() }})"
    )
    .unwrap();
    writeln!(source, "}}\n").unwrap();

    writeln!(source, "pub fn c{case:02}_materialized_between(column: &EncodedColumn, rows: Span, low: i64, high: i64, mode: ClosureMode) -> Result<Execution, String> {{").unwrap();
    writeln!(source, "    if rows.start > rows.end || rows.end > column.truth.len() || low > high {{ return Err(\"materialized BETWEEN invalid\".into()); }} let (values, metrics) = c{case:02}_materialize(column, mode)?; let mut ranges = Vec::new();").unwrap();
    writeln!(source, "    for (offset, value) in values[rows.start..rows.end].iter().enumerate() {{ if value.is_some_and(|value| i128::from(low) <= value && value <= i128::from(high)) {{ let row = rows.start + offset; push_range(&mut ranges, row, row + 1); }} }}").unwrap();
    writeln!(source, "    Ok(Execution {{ answer: Answer::Ranges(ranges), metrics, decoded_rows: values.len() }})").unwrap();
    writeln!(source, "}}\n").unwrap();
}

fn emit_fused_queries(source: &mut String, case: usize, visit: &str) {
    writeln!(source, "pub fn c{case:02}_fused_get_session(column: &EncodedColumn, row: usize, session: &mut ReadSession<'_>) -> Result<Execution, String> {{").unwrap();
    writeln!(source, "    if row >= column.truth.len() {{ return Err(\"fused GET outside column\".into()); }} load_metadata(&column.page, session)?; let mut answer = None; let mut decoded_rows = 0;").unwrap();
    writeln!(source, "    {visit}(session, 0, column.truth.len(), &mut |_session, value, start, end| {{ decoded_rows += end - start; if start <= row && row < end {{ answer = Some(value.map(|value| i64::try_from(value).map_err(|_| \"fused GET value does not fit i64\")).transpose()?); }} Ok(()) }})?;").unwrap();
    writeln!(source, "    Ok(Execution {{ answer: Answer::Value(answer.ok_or(\"fused GET missed row\")?), metrics: session.metrics(), decoded_rows }})").unwrap();
    writeln!(source, "}}\n").unwrap();
    writeln!(source, "pub fn c{case:02}_fused_get(column: &EncodedColumn, row: usize, mode: ClosureMode) -> Result<Execution, String> {{ let mut session = ReadSession::new(&column.page, mode); c{case:02}_fused_get_session(column, row, &mut session) }}\n").unwrap();

    writeln!(source, "pub fn c{case:02}_fused_sum_session(column: &EncodedColumn, rows: Span, session: &mut ReadSession<'_>) -> Result<Execution, String> {{").unwrap();
    writeln!(source, "    if rows.start > rows.end || rows.end > column.truth.len() {{ return Err(\"fused SUM range invalid\".into()); }} load_metadata(&column.page, session)?; let mut sum = 0_i128; let mut decoded_rows = 0;").unwrap();
    writeln!(source, "    {visit}(session, 0, column.truth.len(), &mut |_session, value, start, end| {{ decoded_rows += end - start; let overlap_start = start.max(rows.start); let overlap_end = end.min(rows.end); if overlap_start < overlap_end && let Some(value) = value {{ sum = sum.checked_add(value.checked_mul((overlap_end - overlap_start) as i128).ok_or(\"fused SUM product overflow\")?).ok_or(\"fused SUM overflow\")?; }} Ok(()) }})?;").unwrap();
    writeln!(
        source,
        "    Ok(Execution {{ answer: Answer::Sum(sum), metrics: session.metrics(), decoded_rows }})"
    )
    .unwrap();
    writeln!(source, "}}\n").unwrap();
    writeln!(source, "pub fn c{case:02}_fused_sum(column: &EncodedColumn, rows: Span, mode: ClosureMode) -> Result<Execution, String> {{ let mut session = ReadSession::new(&column.page, mode); c{case:02}_fused_sum_session(column, rows, &mut session) }}\n").unwrap();

    writeln!(source, "pub fn c{case:02}_fused_between_session(column: &EncodedColumn, rows: Span, low: i64, high: i64, session: &mut ReadSession<'_>) -> Result<Execution, String> {{").unwrap();
    writeln!(source, "    if rows.start > rows.end || rows.end > column.truth.len() || low > high {{ return Err(\"fused BETWEEN invalid\".into()); }} load_metadata(&column.page, session)?; let mut ranges = Vec::new(); let mut decoded_rows = 0;").unwrap();
    writeln!(source, "    {visit}(session, 0, column.truth.len(), &mut |_session, value, start, end| {{ decoded_rows += end - start; let overlap_start = start.max(rows.start); let overlap_end = end.min(rows.end); if overlap_start < overlap_end && value.is_some_and(|value| i128::from(low) <= value && value <= i128::from(high)) {{ push_range(&mut ranges, overlap_start, overlap_end); }} Ok(()) }})?;").unwrap();
    writeln!(source, "    Ok(Execution {{ answer: Answer::Ranges(ranges), metrics: session.metrics(), decoded_rows }})").unwrap();
    writeln!(source, "}}\n").unwrap();
    writeln!(source, "pub fn c{case:02}_fused_between(column: &EncodedColumn, rows: Span, low: i64, high: i64, mode: ClosureMode) -> Result<Execution, String> {{ let mut session = ReadSession::new(&column.page, mode); c{case:02}_fused_between_session(column, rows, low, high, &mut session) }}\n").unwrap();
}

fn emit_registries(source: &mut String, count: usize) {
    let signatures = (0..count)
        .map(|case| format!("C{case:02}_PLAN_SIGNATURE"))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        source,
        "pub const PLAN_SIGNATURES: [u64; CASE_COUNT] = [{signatures}];"
    )
    .unwrap();
    writeln!(
        source,
        "pub type GetFn = fn(&EncodedColumn, usize, ClosureMode) -> Result<Execution, String>;"
    )
    .unwrap();
    writeln!(
        source,
        "pub type SumFn = fn(&EncodedColumn, Span, ClosureMode) -> Result<Execution, String>;"
    )
    .unwrap();
    writeln!(source, "pub type BetweenFn = fn(&EncodedColumn, Span, i64, i64, ClosureMode) -> Result<Execution, String>;").unwrap();
    writeln!(source, "pub type FilterFn = fn(&EncodedColumn, i64, i64, ClosureMode) -> Result<Execution, String>;").unwrap();
    writeln!(source, "pub type SumRangesFn = fn(&EncodedColumn, &[Span], ClosureMode) -> Result<Execution, String>;").unwrap();
    writeln!(source, "#[allow(dead_code)]\npub type GetSessionFn = for<'a> fn(&EncodedColumn, usize, &mut ReadSession<'a>) -> Result<Execution, String>;").unwrap();
    writeln!(source, "#[allow(dead_code)]\npub type SumSessionFn = for<'a> fn(&EncodedColumn, Span, &mut ReadSession<'a>) -> Result<Execution, String>;").unwrap();
    writeln!(source, "#[allow(dead_code)]\npub type BetweenSessionFn = for<'a> fn(&EncodedColumn, Span, i64, i64, &mut ReadSession<'a>) -> Result<Execution, String>;").unwrap();
    writeln!(source, "#[allow(dead_code)]\npub type FilterSessionFn = for<'a> fn(&EncodedColumn, i64, i64, &mut ReadSession<'a>) -> Result<Execution, String>;").unwrap();
    writeln!(source, "#[allow(dead_code)]\npub type SumRangesSessionFn = for<'a> fn(&EncodedColumn, &[Span], &mut ReadSession<'a>) -> Result<Execution, String>;").unwrap();
    let list = |suffix: &str| {
        (0..count)
            .map(|case| format!("c{case:02}_{suffix}"))
            .collect::<Vec<_>>()
            .join(", ")
    };
    writeln!(
        source,
        "pub const GET_FNS: [GetFn; CASE_COUNT] = [{}];",
        list("get")
    )
    .unwrap();
    writeln!(
        source,
        "pub const SUM_FNS: [SumFn; CASE_COUNT] = [{}];",
        list("sum")
    )
    .unwrap();
    writeln!(
        source,
        "pub const BETWEEN_FNS: [BetweenFn; CASE_COUNT] = [{}];",
        list("between")
    )
    .unwrap();
    writeln!(
        source,
        "pub const FILTER_FNS: [FilterFn; CASE_COUNT] = [{}];",
        list("filter")
    )
    .unwrap();
    writeln!(
        source,
        "pub const FILTER_SCAN_FNS: [FilterFn; CASE_COUNT] = [{}];",
        list("filter_scan")
    )
    .unwrap();
    writeln!(
        source,
        "pub const SUM_RANGES_FNS: [SumRangesFn; CASE_COUNT] = [{}];",
        list("sum_ranges")
    )
    .unwrap();
    writeln!(
        source,
        "pub const FUSED_SUM_RANGES_FNS: [SumRangesFn; CASE_COUNT] = [{}];",
        list("fused_sum_ranges")
    )
    .unwrap();
    writeln!(
        source,
        "#[allow(dead_code)]\npub const GET_SESSION_FNS: [GetSessionFn; CASE_COUNT] = [{}];",
        list("get_session")
    )
    .unwrap();
    writeln!(
        source,
        "#[allow(dead_code)]\npub const SUM_SESSION_FNS: [SumSessionFn; CASE_COUNT] = [{}];",
        list("sum_session")
    )
    .unwrap();
    writeln!(
        source,
        "#[allow(dead_code)]\npub const BETWEEN_SESSION_FNS: [BetweenSessionFn; CASE_COUNT] = [{}];",
        list("between_session")
    )
    .unwrap();
    writeln!(
        source,
        "#[allow(dead_code)]\npub const FILTER_SESSION_FNS: [FilterSessionFn; CASE_COUNT] = [{}];",
        list("filter_session")
    )
    .unwrap();
    writeln!(source, "#[allow(dead_code)]\npub const FILTER_SCAN_SESSION_FNS: [FilterSessionFn; CASE_COUNT] = [{}];", list("filter_scan_session")).unwrap();
    writeln!(source, "#[allow(dead_code)]\npub const SUM_RANGES_SESSION_FNS: [SumRangesSessionFn; CASE_COUNT] = [{}];", list("sum_ranges_session")).unwrap();
    writeln!(source, "#[allow(dead_code)]\npub const FUSED_SUM_RANGES_SESSION_FNS: [SumRangesSessionFn; CASE_COUNT] = [{}];", list("fused_sum_ranges_session")).unwrap();
    writeln!(
        source,
        "pub const FUSED_GET_FNS: [GetFn; CASE_COUNT] = [{}];",
        list("fused_get")
    )
    .unwrap();
    writeln!(
        source,
        "pub const FUSED_SUM_FNS: [SumFn; CASE_COUNT] = [{}];",
        list("fused_sum")
    )
    .unwrap();
    writeln!(
        source,
        "pub const FUSED_BETWEEN_FNS: [BetweenFn; CASE_COUNT] = [{}];",
        list("fused_between")
    )
    .unwrap();
    writeln!(
        source,
        "#[allow(dead_code)]\npub const FUSED_GET_SESSION_FNS: [GetSessionFn; CASE_COUNT] = [{}];",
        list("fused_get_session")
    )
    .unwrap();
    writeln!(
        source,
        "#[allow(dead_code)]\npub const FUSED_SUM_SESSION_FNS: [SumSessionFn; CASE_COUNT] = [{}];",
        list("fused_sum_session")
    )
    .unwrap();
    writeln!(
        source,
        "#[allow(dead_code)]\npub const FUSED_BETWEEN_SESSION_FNS: [BetweenSessionFn; CASE_COUNT] = [{}];",
        list("fused_between_session")
    )
    .unwrap();
    writeln!(
        source,
        "pub const MATERIALIZED_GET_FNS: [GetFn; CASE_COUNT] = [{}];",
        list("materialized_get")
    )
    .unwrap();
    writeln!(
        source,
        "pub const MATERIALIZED_SUM_FNS: [SumFn; CASE_COUNT] = [{}];",
        list("materialized_sum")
    )
    .unwrap();
    writeln!(
        source,
        "pub const MATERIALIZED_BETWEEN_FNS: [BetweenFn; CASE_COUNT] = [{}];",
        list("materialized_between")
    )
    .unwrap();
    writeln!(
        source,
        "pub const STATIC_GET_FNS: [GetFn; CASE_COUNT] = [{}];",
        list("static_get")
    )
    .unwrap();
    writeln!(
        source,
        "pub const STATIC_SUM_FNS: [SumFn; CASE_COUNT] = [{}];",
        list("static_sum")
    )
    .unwrap();
    writeln!(
        source,
        "pub const STATIC_BETWEEN_FNS: [BetweenFn; CASE_COUNT] = [{}];",
        list("static_between")
    )
    .unwrap();
    writeln!(
        source,
        "pub const STATIC_FILTER_FNS: [FilterFn; CASE_COUNT] = [{}];",
        list("static_filter")
    )
    .unwrap();
}

fn get_name(case: usize, node: usize) -> String {
    format!("c{case:02}_n{node}_get")
}

fn visit_name(case: usize, node: usize) -> String {
    format!("c{case:02}_n{node}_visit")
}

fn static_name(case: usize, node: usize) -> String {
    format!("C{case:02}N{node}Static")
}
